version:  '3.8'
services:
  app:
    image: btphoto:v0.01
    container_name: btphotoflask
    restart: unless-stopped
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
#    volumes:
#      - ./data:/data
